Implement Order List Prototype and UI Enhancements
mobile-dev-16/flutter_app pull request #20
Opened 2024-09-20 23:17 UTC by RaulRinconX

Description: This Pull Request introduces several features and improvements to the order list functionality and UI, including:

- Order Model: The Order model has been updated to include fields such as title, date, and an optional imageUrl. This allows for more flexibility in displaying order information.

- Order Bloc Implementation: The OrderBloc has been implemented to handle the loading of order data. It manages states like OrdersLoading and OrdersLoaded to control the flow of data between the UI and the business logic.

- OrderItem Widget: The OrderItem widget has been created to display individual orders. It shows the order title, formatted date, and an image if available. It also uses the BasicImage widget for consistent image handling, with a placeholder if no image is provided.

- Historical Order List: The order list is treated as a historical record, so the option to delete orders has been removed to preserve the integrity of past orders.

- UI Enhancements: The overall UI of the order list has been improved with better layout and design consistency, including proper handling of images and text overflow.

2024-09-21 21:54 UTC, abelarismendy commented on lib/features/orders/domain/models/order.dart
> +  Order copyWith({
why all params are optional?

2024-09-21 21:56 UTC, abelarismendy commented on lib/features/orders/presentation/bloc/order_item_bloc.dart
separate this file in three different files. _bloc, _event and _state. Create two folders: './order, .'/order_item

2024-09-21 21:59 UTC, abelarismendy requested changes
- Add the new widgets and screen to widgetbook.
- Order item may have more attributes in the future (i.e. state: delivered, in progress, canceled, etc.).
- Separate the bloc, event and state from order_item

2024-09-21 22:02 UTC, abelarismendy requested changes

2024-09-21 22:02 UTC, abelarismendy commented on lib/features/orders/presentation/widgets/order_item.dart
> +            // Usamos BasicImage para mostrar la imagen
delete comments

2024-09-21 22:02 UTC, abelarismendy commented on lib/features/orders/presentation/widgets/order_item.dart
> +                          order.title, // Usamos `title` para el nombre del pedido
delete comments

2024-09-21 22:02 UTC, abelarismendy commented on lib/features/orders/presentation/widgets/order_item.dart
> +                            'Delivered: ${DateFormat.yMMMd().format(order.date)}', // Mostramos la fecha formateada
implement this in ./core/utils/
see format_price.dart

2024-09-21 22:02 UTC, abelarismendy commented on lib/features/orders/presentation/widgets/order_item.dart
> +                            'Delivered: ${DateFormat.yMMMd().format(order.date)}', // Mostramos la fecha formateada
delete comments

2024-09-21 22:06 UTC, abelarismendy commented on lib/features/orders/presentation/widgets/order_item.dart
> +                            'Delivered: ${DateFormat.yMMMd().format(order.date)}', // Mostramos la fecha formateada
@RaulRinconX

2024-09-26 01:11 UTC, RaulRinconX commented on lib/features/orders/domain/models/order.dart
> +  Order copyWith({
Solved

2024-09-26 03:48 UTC, closed without merging